[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-yaml" },
  { id = "check-toml" },
  { id = "check-added-large-files" },
  { id = "check-merge-conflict" },
  { id = "debug-statements" },
]

[[repos]]
hooks = [{
    id = "ruff-check",
    name = "ruff check",
    language = "system",
    entry = "ruff check --fix",
    files = "\\.py$",
  },
  {
    id = "ruff-format",
    name = "ruff format",
    language = "system",
    entry = "ruff format",
    files = "\\.py$",
  },
  {
    id = "ty-check",
    name = "ty check",
    language = "system",
    entry = "ty check",
    files = "\\.py$",
  },
  {
    id = "check-dependencies",
    name = "Check Imports against pyproject.toml",
    language = "system",
    entry = "python .github/scripts/check_imports.py",
    pass_filenames= false,
    files = "\\.py$, pyproject.toml",
  }]
repo = "local"
